### PR TITLE
Add RWLock to wire.Session

### PR DESCRIPTION
**Pull request by mixmasala**
Don't merge this, I haven't tested recently to see if it fixes a race; did we fix the issue this is trying to resolve?

### CODE REVIEW

**Comment by david415** [comment]
why does this PR exist? what problem is it trying to solve that we didn't already solve?

**Comment by mixmasala** [comment]
ah, I'm sure this branch was created to fix some sort of race/crash, but I don't know if we fixed it elsewhere yet. I'm going through stale branches and pruning stuff that is irrelevant.

**Comment by david415** [comment]
as far as i know we fixed all the races.

**Comment by mixmasala** [comment]
https://github.com/katzenpost/mixnet_uprising/issues/74

I'm not sure if this issue was resolved or moved around a bunch and lost track of. What commit resolved it?

**Comment by david415** [comment]
yes that's a report about a race in the server... we should build the server with the race detector and run it to see what happens. really, this should just be a normal part of our integration testing system and done automatically with some such mechanism that doesn't have to be travis.

**Comment by david415** [comment]
anyway we cannot merge this PR unless we find it fixes a bug.. and that it's not causing any. closing for now.

**Pull request closed without merging**
